name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - main
 
permissions:
  contents: read
  pages: write
  id-token: write
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      - name: Authorize Git
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
      - name: Update submodule
        run: |
          git submodule update  --init --recursive --remote -f
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Clone Quartz
        run: git clone https://github.com/jackyzha0/quartz.git
      - name: Initialize quartz deps 
        working-directory: quartz
        run: npm i
      - name: Create static content
        working-directory: quartz
        run: npx quartz create -s ../docs -l shortest -X copy
      - name: Build Quartz
        working-directory: quartz
        run: npx quartz build
      - name: CD list
        working-directory: quartz/public
        run: ls .
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz/public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
