name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - main
 
permissions:
  contents: read
  pages: write
  id-token: write
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Clone Quartz
        run: git clone https://github.com/jackyzha0/quartz.git
      - name: Initialize quartz deps 
        working-directory: quartz
        run: npm i
      - name: CD list
        working-directory: quartz
        run: ls .
      - name: Create static content
        working-directory: quartz
        run: npx quartz create -s ../docs -l shortest -X new
      - name: Build Quartz
        working-directory: quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz/content
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
